### ISSUE TITLE
Missing traits... 

### ISSUE THREAD

**Issue by nurmohammed840** [brunohkbx/react-native-material-backdrop-modal#168]
1. Subheader should optional
2. Modal shouldn't drop if contain height is limited! Currently only Subheader is visible 
3. Modal should blur when focused   
4. When focused. Taping on Modal should make it unfocused.
5. Needed to refactor API...

I don't have enough knowledge about frontend tech. But I want to collaborate.

**Comment by brunohkbx** [comment]
Hello @nurmohammed840. Thanks for listing it. Unfortunately, I couldn't come up with an approach to make the Backdrop adapt according to the height of the container.

If you want to give it a try, PRs are welcome.
